### ISSUE TITLE
Can not send message

### ISSUE THREAD

**Issue by mavericklou** [AdamClements/quit-yo-jibber#3]
``` clojure
(send-message conn "person@gmail.com" "I wouldn't like not to speak unless spoken to")
```

This send-message function doesn't work. Could be out-dated smack version issue?
The message handler and presence handler are working correctly.

**Comment by AdamClements** [comment]
Does the handle-message version work to respond to an incoming message? 

Are you using Google hangouts? They have officially dropped support for xmpp, which means sometimes random things will break! That's the main reason I haven't done much with this library for a while - Google kept breaking things for no good reason. 

If you want to try with an updated smack library, you should be able to just add it as a dependency in your own project.clj assuming they haven't made any backwards incompatible changes.
